services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./project/db:/app/project/db
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
